### ISSUE TITLE
Move To interaction from NotePlan

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/agenda-obsidian#3]
When moving a task, link to the original task. This could optionally use Obsidian block-level links. What would it look like if a task is moved multiple times? Should it be left on each day that it was not completed?

<img width="322" alt="MovedTask" src="https://user-images.githubusercontent.com/597386/101113015-68a74c00-35d6-11eb-8203-430254b3acfb.png">

**Comment by liamcain** [comment]
Philosophically, how are you thinking about the "brain" of the plugin? Is all information a reflection of the markdown input? Or is there metadata/db powering it outside the vault markdown?

**Comment by tgrosinger** [comment]
I think it's very important that everything is within the vault and in markdown. Adding tasks should be easy to do from my phone in a standard markdown app.

That is the same reason that I also think a task should be a `- [ ] my task` and not a new note. Creating a new file and linking it to the right place is much harder on my phone than adding a new bullet point in my daily note or inbox note.

So far I think "metadata" either needs to be inline (such as the image above, or like how todo.txt operates) or in a sub-list of that task.

org-mode has the benefits of being its own syntax, and they use properties drawers to store info about previous repetitions and the lines after a task for dates, for example:

```
* TODO Pick up Sam at school
  <2007-05-16 Wed 12:30 +1w>
```

**Comment by tgrosinger** [comment]
Integrated this idea into latest version of README.md
